sonar.projectKey=Vytor-Oliveira_BuscaLed
sonar.organization=vytor-oliveira

sonar.projectName=BuscaLED
sonar.sources=backend/src,frontend/src
sonar.tests=backend/src,frontend/src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/*.config.js,**/coverage/**

sonar.sourceEncoding=UTF-8
